// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN1K7XJg0LBPuhTUSs43QuWJVpJvYWtL4',
    appId: '1:125581223747:web:03d9caed10d93dae21f1f6',
    messagingSenderId: '125581223747',
    projectId: 'devri-chat-app',
    authDomain: 'devri-chat-app.firebaseapp.com',
    storageBucket: 'devri-chat-app.firebasestorage.app',
    measurementId: 'G-5KY6E76C8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ZhYNRiPzCzjrQOn_fm1MxW-aFZCDFm0',
    appId: '1:125581223747:android:f4923032dee6f3a021f1f6',
    messagingSenderId: '125581223747',
    projectId: 'devri-chat-app',
    storageBucket: 'devri-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeu1_IlEDpPRbRWiDQRicEn4L5tf8Vn3o',
    appId: '1:125581223747:ios:7692c7fbe0cdbe1f21f1f6',
    messagingSenderId: '125581223747',
    projectId: 'devri-chat-app',
    storageBucket: 'devri-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeu1_IlEDpPRbRWiDQRicEn4L5tf8Vn3o',
    appId: '1:125581223747:ios:7692c7fbe0cdbe1f21f1f6',
    messagingSenderId: '125581223747',
    projectId: 'devri-chat-app',
    storageBucket: 'devri-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN1K7XJg0LBPuhTUSs43QuWJVpJvYWtL4',
    appId: '1:125581223747:web:168fa30f7ef418e021f1f6',
    messagingSenderId: '125581223747',
    projectId: 'devri-chat-app',
    authDomain: 'devri-chat-app.firebaseapp.com',
    storageBucket: 'devri-chat-app.firebasestorage.app',
    measurementId: 'G-4M919NFW59',
  );
}
